### ISSUE TITLE
Некорректная дока для overloard

### ISSUE THREAD

**Issue by alekson** [yandex/yandex-tank#465]
https://overload.yandex.net/mainpage/guide#install

Конфиг сходу не работает, сначала нужно перевести в yaml, а потом узнать что модуль tank требует непонятный package

Рабочий вариант после гугления стал выглядеть так, думаю стоит поправить и сэкономить кому то пару часов.

```
overload:
  enabled: true
  package: yandextank.plugins.DataUploader
  token_file: "token.txt"
phantom:
  address: example.com:443
  ssl: true
  load_profile:
    load_type: rps
    schedule: line(1, 10, 1m)
  uris: |
    /
    /page1
    /page2
telegraf:
  enabled: false
```
