### ISSUE TITLE
yandextank-1.9.10 Errorr: headers: [must be of list type] 

### ISSUE THREAD

**Issue by vveliev** [yandex/yandex-tank#540]
having problem running yandex 1.9.10 , 1.9.3 does work
```
Successfully installed yandextank-1.9.10
(appenv) root@ce64498a01d2:/var/loadtest# yandex-tank -c load.yaml
18:54:35 [WARNING] /etc/yandex-tank is not accessible to get configs list
/appenv/local/lib/python2.7/site-packages/yandextank/plugins/Phantom/reader.py:14: FutureWarning: The pandas.parser module is deprecated and will be removed in a future version. Please import from pandas.io.parser instead
  from pandas.parser import CParserError
18:54:35 [ERROR] Exception: Validation error:
phantom:
  headers: [must be of list type]
  uris: [must be of list typе]
```

load.yml

```  
  headers: |
      [accept: application/json]
      [content-type: application/json]
      [X-Auth-Api-Key: 8457a6ad16b34a8c8b0498e50849d9cf]
  uris: |
    /app/ping
```

**Comment by vveliev** [comment]
format change since 1.9.8

```
  headers:
    - 'accept: application/json'
    - 'content-type: application/json'
    - 'X-Auth-Api-Key: 8457a6ad16b34a8c8b0498e50849d9cf'
  uris:
    - /app/ping
```
