### ISSUE TITLE
[ERROR] Exception: No module named Jmeter

### ISSUE THREAD

**Issue by sibilkov** [yandex/yandex-tank#550]
Hi! I have error then I try to use my Jmeter script 

> [ERROR] Exception: No module named Jmeter

Yandex Tank version: 1.9.11
I have the same error then I try to use docker with direvius/yandex-tank image.

My load.yaml config:
```
phantom:
  enabled: false

jmeter:
  package: yandextank.plugins.Jmeter
  enabled: true
  jmx: test.myres.com.jmx 

overload:
  enabled: true
  package: yandextank.plugins.DataUploader
  token_file: token.txt
  job_name: tests
  job_dsc: tests
```
