### ISSUE TITLE
yandex-tank starts to get connection refused after some time

### ISSUE THREAD

**Issue by mikhmakarov** [yandex/yandex-tank#650]
I use yandex-tank (docker version) to test my server. At first (first half of a minute) everything goes smoothly (I get all 200 return codes), but then I start to get lots of connection timeout and connection refused. Then I decided to retest with google.com (see config below) instead of my server. Still I get the same error. What are the possible reasons for such behaviour?

```
phantom:
  writelog: all
  address: google.com # [Target's address]:[target's port]
  instances: 10000
  uris:
    - /
  load_profile:
    load_type: rps # schedule load by defining requests per second
    schedule: const(100, 1m) 
console:
  enabled: true # enable console output
telegraf:
  enabled: true
```
