### ISSUE TITLE
Options "phantom.cache_dir" and "phantom.use_cache" are ignored

### ISSUE THREAD

**Issue by timur-gilauri** [yandex/yandex-tank#697]
## Options "phantom.cache_dir" and "phantom.use_cache" are ignored. 

There is temporary directory for every test and everything works right except cache. Tank ignores "use_cache" option and still creates .stpd file and put that file into the directory where yandex-tank runs from instead of that mentioned in "cache_dir" option.

```
phantom:
  ammo_type: uri
  address: url.ru
  load_profile:
    load_type: rps
    schedule: step(100,500,100,20)
  use_caching: false
  instances: 5000
  ammofile: /tmp/tank-test-vzBjPX/ammo.txt
  cache_dir: /tmp/tank-test-vzBjPX/
console:
  enabled: true
telegraf:
  enabled: false
core:
  artifacts_base_dir: /tmp/tank-test-vzBjPX/logs
  artifacts_dir: /tmp/tank-test-vzBjPX/logs/
```
