### ISSUE TITLE
Yandex tank with pandora unknown flag

### ISSUE THREAD

**Issue by webchi** [yandex/yandex-tank#740]
Танк запускает pandora с неизвестным параметром
[INFO] Starting: ['pandora', '-expvar', '/myfolder/test/load/logs/2019-05-08_11-26-43.110160/pandora_config_kzX56J.yaml']

load.yml
```
phantom:
  enabled: false
pandora:
  package: yandextank.plugins.Pandora
  enabled: true
  pandora_cmd: pandora 
  config_file: pandora_config.yml 
console:
  enabled: true # enable console output
telegraf:
  enabled: false
```
log:
```
flag provided but not defined: -expvar
Usage of Pandora: pandora [<config_filename>]
<config_filename> is './load.(yaml|json|...)' by default
  -example
    	print example config to STDOUT and exit
```
