### ISSUE TITLE
TLS SNI support in yandex-tank with phantom

### ISSUE THREAD

**Issue by maxt** [yandex/yandex-tank#895]
Hello!
My test scenario implies interaction with https endpoint which relies on TLS SNI.

As far as I understand, yandex-tank generates config for phantom loader, and despite I specify hostname and port in load.yml it uses IP address for this configuration, so, phantom doesn't have an information about hostname => it can't provide ongoing secure connection with SNI field. 
So, my endpoint can't determine destination of ingoing connection and just throws 503 and service doesn't exist error code. 

My environment is openshift and traffic is going through openshift route to istio ingress gateway which terminates tls connection.

**Comment by Antik9421** [comment]
some problem 
```
2026-05-22 14:51:36.970 +0000 [error] [benchmark_io 009] SSL error:14094458:SSL routines:ssl3_read_bytes:tlsv1 unrecognized name
2026-05-22 14:51:36.970 +0000 [error] [benchmark_io 009] SSL_connect error 1
```

```
autostop:
  autostop:
  - http(5xx,10%,5s)
  - time(5s,10s)
  - net(xx,10,30)
  - http(429,10%,5s)
console:
  enabled: true
overload:
  enabled: false
  job_dsc: Stress and load tests performed uppon client request
  job_name: Result of stress and load testing for the website with page categorization
    and real users behavior
  package: yandextank.plugins.DataUploader
  token_file: token.txt
phantom:
  address: x.x.x.x:443 
  ammofile: ammo.txt
  header_http: '1.1'
  load_profile:
    load_type: rps
    schedule: line(2, 200, 20m)
  ssl: true
telegraf:
  enabled: false

```

TCP DUMP

```
   90   3.630480 138.199.238.157 → 167.99.221.195 TLSv1 355 Client Hello
   91   3.647340 167.99.221.195 → 138.199.238.157 TCP 72 443 → 43616 [ACK] Seq=1 Ack=284 Win=64896 Len=0 TSval=2399678410 TSecr=803845910
   92   3.647443 167.99.221.195 → 138.199.238.157 TLSv1.2 79 Alert (Level: Fatal, Description: Unrecognized Name)
   93   3.647485 138.199.238.157 → 167.99.221.195 TCP 72 43616 → 443 [ACK] Seq=284 Ack=8 Win=64256 Len=0 TSval=803845927 TSecr=2399678410
   94   3.647518 167.99.221.195 → 138.199.238.157 TCP 72 443 → 43616 [FIN, ACK] Seq=8 Ack=284 Win=64896 Len=0 TSval=2399678411 TSecr=803845910
   95   3.648064 138.199.238.157 → 167.99.221.195 TCP 72 43616 → 443 [FIN, ACK] Seq=284 Ack=9 Win=64256 Len=0 TSval=803845927 TSecr=2399678411
   96   3.664844 167.99.221.195 → 138.199.238.157 TCP 72 443 → 43616 [ACK] Seq=9 Ack=285 Win=64896 Len=0 TSval=2399678428 TSecr=803845927
   97   3.997018 138.199.238.157 → 167.99.221.195 TCP 80 43620 → 443 [SYN] Seq=0 Win=64240 Len=0 MSS=1460 SACK_PERM TSval=803846276 TSecr=0 WS=128
   98   4.008576 167.99.221.195 → 138.199.238.157 TCP 80 443 → 43620 [SYN, ACK] Seq=0 Ack=1 Win=65160 Len=0 MSS=1460 TSval=2399678771 TSecr=803846276 WS=128
   99   4.008688 138.199.238.157 → 167.99.221.195 TCP 72 43620 → 443 [ACK] Seq=1 Ack=1 Win=64256 Len=0 TSval=803846288 TSecr=2399678771
  100   4.009165 138.199.238.157 → 167.99.221.195 TLSv1 355 Client Hello
  101   4.020723 167.99.221.195 → 138.199.238.157 TCP 72 443 → 43620 [ACK] Seq=1 Ack=284 Win=64896 Len=0 TSval=2399678783 TSecr=803846288
  102   4.020723 167.99.221.195 → 138.199.238.157 TLSv1.2 79 Alert (Level: Fatal, Description: Unrecognized Name)
  103   4.020724 167.99.221.195 → 138.199.238.157 TCP 72 443 → 43620 [FIN, ACK] Seq=8 Ack=284 Win=64896 Len=0 TSval=2399678784 TSecr=803846288
  104   4.020817 138.199.238.157 → 167.99.221.195 TCP 72 43620 → 443 [ACK] Seq=284 Ack=8 Win=64256 Len=0 TSval=803846300 TSecr=2399678784

```
